// Code generated by hertz generator.

package video

import (
	"context"

	api "myreel/app/gateway/model/api/video"
	"myreel/app/gateway/pack"
	"myreel/app/gateway/rpc"
	"myreel/kitex_gen/video"
	"myreel/pkg/constants"
	"myreel/pkg/errno"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// VideoStream .
// @router /api/v1/video/feed [GET]
func VideoStream(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.VideoStreamRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamVerifyError.WithError(err))
		return
	}

	data, err := rpc.VideoSteamRPC(ctx, &video.VideoStreamRequest{
		LatestTime: req.LatestTime,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespData(c, data)
}

// PublishList .
// @router /api/v1/video/list [GET]
func PublishList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.PublishListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.PublishListResponse)

	c.JSON(consts.StatusOK, resp)
}

// Popular .
// @router /api/v1/video/popular [GET]
func Popular(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.PopularRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.PopularResponse)

	c.JSON(consts.StatusOK, resp)
}

// Search .
// @router /api/v1/video/search [POST]
func Search(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.SearchRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.SearchResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetVideoUploadToken .
// @router /api/v1/video/upload/token [POST]
func GetVideoUploadToken(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.GetVideoUploadTokenRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamVerifyError.WithError(err))
		return
	}

	val, exist := c.Get(constants.CtxUserIdKey)
	if !exist {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}
	uid, ok := val.(int64)
	if !ok {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}
	data, err := rpc.GetVideoUploadTokenRPC(ctx, &video.GetVideoUploadTokenRequest{
		Suffix: req.Suffix,
		UserId: uid,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespData(c, data)
}
