// Code generated by hertz generator.

package video

import (
	"context"

	api "myreel/app/gateway/model/api/video"
	"myreel/app/gateway/pack"
	"myreel/app/gateway/rpc"
	"myreel/kitex_gen/video"
	"myreel/pkg/constants"
	"myreel/pkg/errno"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// VideoStream .
// @router /api/v1/video/feed [GET]
func VideoStream(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.VideoStreamRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamVerifyError.WithError(err))
		return
	}

	data, err := rpc.VideoSteamRPC(ctx, &video.VideoStreamRequest{
		LatestTime: req.LatestTime,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespData(c, data)
}

// PublishList .
// @router /api/v1/video/list [GET]
func PublishList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.PublishListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamVerifyError.WithError(err))
		return
	}
	val, exist := c.Get(constants.CtxUserIdKey)
	if !exist {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}
	uid, ok := val.(int64)
	if !ok {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
	}

	data, err := rpc.PublishListRPC(ctx, &video.PublishListRequest{
		Cursor: req.Cursor,
		Limit:  req.Limit,
		Uid:    uid,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespData(c, data)
}

// Popular .
// @router /api/v1/video/popular [GET]
func Popular(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.PopularRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamVerifyError.WithError(err))
		return
	}

	data, err := rpc.PopularRPC(ctx, &video.PopularRequest{
		Cursor: req.Cursor,
		Limit:  req.Limit,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespData(c, data)
}

// Search .
// @router /api/v1/video/search [POST]
func Search(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.SearchRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.SearchResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetVideoUploadToken .
// @router /api/v1/video/upload/token [POST]
func GetVideoUploadToken(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetVideoUploadTokenRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamVerifyError.WithError(err))
		return
	}

	val, exist := c.Get(constants.CtxUserIdKey)
	if !exist {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}
	uid, ok := val.(int64)
	if !ok {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}
	data, err := rpc.GetVideoUploadTokenRPC(ctx, &video.GetVideoUploadTokenRequest{
		Suffix: req.Suffix,
		UserId: uid,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespData(c, data)
}

// GetVideoCoverUploadToken .
// @router /api/v1/video/cover/upload/token [POST]
func GetVideoCoverUploadToken(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetVideoCoverUploadTokenRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamVerifyError.WithError(err))
		return
	}

	val, exist := c.Get(constants.CtxUserIdKey)
	if !exist {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}
	uid, ok := val.(int64)
	if !ok {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}
	data, err := rpc.GetVideoCoverUploadTokenRPC(ctx, &video.GetVideoCoverUploadTokenRequest{
		Suffix: req.Suffix,
		UserId: uid,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespData(c, data)
}

// SaveVideo .
// @router api/v1/video/publish [POST]
func SaveVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.SaveVideoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamVerifyError.WithError(err))
		return
	}

	val, exist := c.Get(constants.CtxUserIdKey)
	if !exist {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}
	uid, ok := val.(int64)
	if !ok {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}
	err = rpc.SaveVideoRPC(ctx, &video.SaveVideoRequest{
		Title:       req.Title,
		Description: req.Description,
		CoverUrl:    req.CoverUrl,
		VideoUrl:    req.VideoUrl,
		UserId:      uid,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespSuccess(c)
}
