// Code generated by Kitex v0.15.2. DO NOT EDIT.

package videoservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	video "myreel/kitex_gen/video"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	VideoStream(ctx context.Context, Req *video.VideoStreamRequest, callOptions ...callopt.Option) (r *video.VideoStreamResponse, err error)
	GetVideoUploadToken(ctx context.Context, Req *video.GetVideoUploadTokenRequest, callOptions ...callopt.Option) (r *video.GetVideoUploadTokenResponse, err error)
	GetVideoCoverUploadToken(ctx context.Context, Req *video.GetVideoCoverUploadTokenRequest, callOptions ...callopt.Option) (r *video.GetVideoCoverUploadTokenResponse, err error)
	SaveVideo(ctx context.Context, Req *video.SaveVideoRequest, callOptions ...callopt.Option) (r *video.SaveVideoResponse, err error)
	PublishList(ctx context.Context, Req *video.PublishListRequest, callOptions ...callopt.Option) (r *video.PublishListResponse, err error)
	Popular(ctx context.Context, Req *video.PopularRequest, callOptions ...callopt.Option) (r *video.PopularResponse, err error)
	Search(ctx context.Context, Req *video.SearchRequest, callOptions ...callopt.Option) (r *video.SearchResponse, err error)
	VideoLikeAction(ctx context.Context, Req *video.VideoLikeActionRequest, callOptions ...callopt.Option) (r *video.VideoLikeActionResponse, err error)
	GetVideosByIds(ctx context.Context, Req *video.GetVideosByIdsRequest, callOptions ...callopt.Option) (r *video.GetVideosByIdsResponse, err error)
	AddCommentCount(ctx context.Context, Req *video.AddCommentCountRequest, callOptions ...callopt.Option) (r *video.AddCommentCountResponse, err error)
	CheckVideoUser(ctx context.Context, Req *video.CheckVideoUserRequest, callOptions ...callopt.Option) (r *video.CheckVideoUserResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kVideoServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kVideoServiceClient struct {
	*kClient
}

func (p *kVideoServiceClient) VideoStream(ctx context.Context, Req *video.VideoStreamRequest, callOptions ...callopt.Option) (r *video.VideoStreamResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.VideoStream(ctx, Req)
}

func (p *kVideoServiceClient) GetVideoUploadToken(ctx context.Context, Req *video.GetVideoUploadTokenRequest, callOptions ...callopt.Option) (r *video.GetVideoUploadTokenResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetVideoUploadToken(ctx, Req)
}

func (p *kVideoServiceClient) GetVideoCoverUploadToken(ctx context.Context, Req *video.GetVideoCoverUploadTokenRequest, callOptions ...callopt.Option) (r *video.GetVideoCoverUploadTokenResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetVideoCoverUploadToken(ctx, Req)
}

func (p *kVideoServiceClient) SaveVideo(ctx context.Context, Req *video.SaveVideoRequest, callOptions ...callopt.Option) (r *video.SaveVideoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SaveVideo(ctx, Req)
}

func (p *kVideoServiceClient) PublishList(ctx context.Context, Req *video.PublishListRequest, callOptions ...callopt.Option) (r *video.PublishListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishList(ctx, Req)
}

func (p *kVideoServiceClient) Popular(ctx context.Context, Req *video.PopularRequest, callOptions ...callopt.Option) (r *video.PopularResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Popular(ctx, Req)
}

func (p *kVideoServiceClient) Search(ctx context.Context, Req *video.SearchRequest, callOptions ...callopt.Option) (r *video.SearchResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Search(ctx, Req)
}

func (p *kVideoServiceClient) VideoLikeAction(ctx context.Context, Req *video.VideoLikeActionRequest, callOptions ...callopt.Option) (r *video.VideoLikeActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.VideoLikeAction(ctx, Req)
}

func (p *kVideoServiceClient) GetVideosByIds(ctx context.Context, Req *video.GetVideosByIdsRequest, callOptions ...callopt.Option) (r *video.GetVideosByIdsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetVideosByIds(ctx, Req)
}

func (p *kVideoServiceClient) AddCommentCount(ctx context.Context, Req *video.AddCommentCountRequest, callOptions ...callopt.Option) (r *video.AddCommentCountResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddCommentCount(ctx, Req)
}

func (p *kVideoServiceClient) CheckVideoUser(ctx context.Context, Req *video.CheckVideoUserRequest, callOptions ...callopt.Option) (r *video.CheckVideoUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckVideoUser(ctx, Req)
}
