// Code generated by hertz generator.

package follow

import (
	"myreel/app/gateway/mv"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followeredMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followeredlistMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		mv.Auth(),
	}
}

func _followingMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		mv.Auth(),
	}
}

func _friendsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _friendlistMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		mv.Auth(),
	}
}

func _relationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followactionMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		mv.Auth(),
	}
}

func _followeringlistMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		mv.Auth(),
	}
}

func _chatgroupMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		mv.Auth(),
	}
}

func _groupMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createdchatgrouplistMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		mv.Auth(),
	}
}

func _joinedchatgrouplistMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		mv.Auth(),
	}
}
