// Code generated by hertz generator.

package follow

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followeredMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followeredlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followinglistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _friendsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _friendlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followactionMw() []app.HandlerFunc {
	// your code...
	return nil
}
