// Code generated by Kitex v0.15.2. DO NOT EDIT.

package like

import (
	"context"
	"myreel/kitex_gen/model"
	"myreel/kitex_gen/video"

	"github.com/cloudwego/prutal"
)

type LikeActionRequest struct {
	VideoId    string `protobuf:"bytes,1,opt,name=videoId" json:"videoId,omitempty"`
	CommentId  string `protobuf:"bytes,2,opt,name=commentId" json:"commentId,omitempty"`
	ActionType int64  `protobuf:"varint,3,opt,name=actionType" json:"actionType,omitempty"`
}

func (x *LikeActionRequest) Reset() { *x = LikeActionRequest{} }

func (x *LikeActionRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *LikeActionRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LikeActionRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *LikeActionRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *LikeActionRequest) GetActionType() int64 {
	if x != nil {
		return x.ActionType
	}
	return 0
}

type LikeActionResponse struct {
	Base *model.BaseResp `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	Msg  string          `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (x *LikeActionResponse) Reset() { *x = LikeActionResponse{} }

func (x *LikeActionResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *LikeActionResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LikeActionResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *LikeActionResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type LikeListRequest struct {
	Uid    string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	Cursor int64  `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"`
	Limit  int64  `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
}

func (x *LikeListRequest) Reset() { *x = LikeListRequest{} }

func (x *LikeListRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *LikeListRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LikeListRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *LikeListRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *LikeListRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type LikeListResponse struct {
	Base *model.BaseResp  `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	Data *video.VideoList `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (x *LikeListResponse) Reset() { *x = LikeListResponse{} }

func (x *LikeListResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *LikeListResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LikeListResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *LikeListResponse) GetData() *video.VideoList {
	if x != nil {
		return x.Data
	}
	return nil
}

type LikeService interface {
	LikeAction(ctx context.Context, req *LikeActionRequest) (res *LikeActionResponse, err error)
	LikeList(ctx context.Context, req *LikeListRequest) (res *LikeListResponse, err error)
}
