// Code generated by hertz generator.

package chat

import (
	"context"
	"log"
	"myreel/app/gateway/handler/api/chat/pack"
	"myreel/app/gateway/rpc"
	"myreel/kitex_gen/chat"
	"myreel/pkg/constants"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/hertz-contrib/websocket"
)

// Chat .
// @router /chat [GET]
func Chat(ctx context.Context, c *app.RequestContext) {
	val, exist := c.Get(constants.CtxUserIdKey)
	if !exist {
		c.AbortWithStatus(consts.StatusBadRequest)
		return
	}
	uid, ok := val.(int64)
	if !ok {
		c.AbortWithStatus(consts.StatusBadRequest)
		return
	}

	var upgrader = websocket.HertzUpgrader{}
	err := upgrader.Upgrade(c, func(conn *websocket.Conn) {

		for {
			mt, message, err := conn.ReadMessage()
			if err != nil {
				log.Println("read:", err)
				break
			}
			msg, err := pack.ParseMessage(message)
			if err != nil {
				log.Println("failed to parse message:", err)
				c.AbortWithStatus(consts.StatusBadRequest)
				return
			}
			switch msg.Type {
			case pack.TypePrivateMessage:
				privateMsg, err := pack.ParsePrivateMsg(msg.Data)
				if err != nil {
					log.Println("failed to parse privateMsg:", err)
					c.AbortWithStatus(consts.StatusBadRequest)
					return
				}
				err = rpc.SendMessageRPC(ctx, &chat.SendMessageRequest{
					SenderId: uid,
					TargetId: privateMsg.TargetId,
					ChatType: chat.ChatType_CHAT_TYPE_PRIVATE,
					Content:  privateMsg.Content,
				})
				if err != nil {
					log.Println("failed to send private message:", err)
					c.AbortWithStatus(consts.StatusBadRequest)
					return
				}
			case pack.TypePrivateHistory:

			case pack.TypePrivateUnread:

			case pack.TypeGroupMessage:

			case pack.TypeGroupHistory:

			default:
				log.Println("type is error")
				c.AbortWithStatus(consts.StatusBadRequest)
				return
			}
			err = conn.WriteMessage(mt, message)
			if err != nil {
				log.Println("failed to write return message:", err)
				c.AbortWithStatus(consts.StatusBadRequest)
				return
			}
		}
	})
	if err != nil {
		log.Print("upgrade:", err)
		c.AbortWithStatus(consts.StatusBadRequest)
		return
	}
}
