// Code generated by hertz generator.

package chat

import (
	"context"
	"log"
	"myreel/app/gateway/handler/api/chat/pack"
	"myreel/app/gateway/rpc"
	"myreel/kitex_gen/chat"
	"myreel/pkg/constants"
	"strconv"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/hertz-contrib/websocket"
)

// Chat .
// @router /chat [GET]
func Chat(ctx context.Context, c *app.RequestContext) {
	val, exist := c.Get(constants.CtxUserIdKey)
	if !exist {
		c.AbortWithStatus(consts.StatusBadRequest)
		return
	}
	uid, ok := val.(int64)
	if !ok {
		c.AbortWithStatus(consts.StatusBadRequest)
		return
	}

	var upgrader = websocket.HertzUpgrader{}
	err := upgrader.Upgrade(c, func(conn *websocket.Conn) {

		for {
			mt, message, err := conn.ReadMessage()
			if err != nil {
				log.Println("read:", err)
				break
			}
			msg, err := pack.ParseWSMessage(message)
			if err != nil {
				log.Println("failed to parse message:", err)
				c.AbortWithStatus(consts.StatusBadRequest)
				return
			}
			switch msg.Type {
			case pack.TypePrivateMessage:
				sendReq, err := pack.ParseSendRequest(msg.Data)
				if err != nil {
					log.Println("failed to parse send request:", err)
					c.AbortWithStatus(consts.StatusBadRequest)
					return
				}
				targetId, err := strconv.ParseInt(sendReq.TargetId, 10, 64)
				if err != nil {
					log.Println("failed to parse target id:", err)
					c.AbortWithStatus(consts.StatusBadRequest)
					return
				}
				err = rpc.SendMessageRPC(ctx, &chat.SendMessageRequest{
					SenderId: uid,
					TargetId: targetId,
					ChatType: chat.ChatType_CHAT_TYPE_PRIVATE,
					Content:  sendReq.Content,
				})
				if err != nil {
					log.Println("failed to send message:", err)
					c.AbortWithStatus(consts.StatusBadRequest)
					return
				}
				message, err = pack.MarshalWSMessage(&pack.WSMessage{
					Type: msg.Type,
					Data: "success",
				})
				if err != nil {
					log.Println("failed to marshal ws message", err)
					c.AbortWithStatus(consts.StatusBadRequest)
					return
				}
			case pack.TypePrivateHistory:
				historyReq, err := pack.ParseHistoryRequest(msg.Data)
				if err != nil {
					log.Println("failed to parse history request:", err)
					c.AbortWithStatus(consts.StatusBadRequest)
					return
				}
				targetId, err := strconv.ParseInt(historyReq.TargetId, 10, 64)
				if err != nil {
					log.Println("failed to parse target id:", err)
					c.AbortWithStatus(consts.StatusBadRequest)
					return
				}
				messageList, err := rpc.GetHistoryMessagesRPC(ctx, &chat.GetHistoryRequest{
					UserId:   uid,
					TargetId: targetId,
					ChatType: chat.ChatType_CHAT_TYPE_PRIVATE,
					Cursor:   historyReq.Cursor,
					Limit:    historyReq.Limit,
				})
				if err != nil {
					log.Println("failed to send message:", err)
					c.AbortWithStatus(consts.StatusBadRequest)
					return
				}
				message, err = pack.MarshalWSMessage(&pack.WSMessage{
					Type: msg.Type,
					Data: messageList,
				})
				if err != nil {
					log.Println("failed to marshal ws message", err)
					c.AbortWithStatus(consts.StatusBadRequest)
					return
				}
			case pack.TypePrivateUnread:
				unreadReq, err := pack.ParseUnreadRequest(msg.Data)
				if err != nil {
					log.Println("failed to parse unread request:", err)
					c.AbortWithStatus(consts.StatusBadRequest)
					return
				}
				targetId, err := strconv.ParseInt(unreadReq.TargetId, 10, 64)
				if err != nil {
					log.Println("failed to parse target id:", err)
					c.AbortWithStatus(consts.StatusBadRequest)
					return
				}
				messageList, err := rpc.GetUnreadMessagesRPC(ctx, &chat.GetUnreadRequest{
					UserId:   uid,
					TargetId: targetId,
					ChatType: chat.ChatType_CHAT_TYPE_PRIVATE,
				})
				if err != nil {
					log.Println("failed to send message:", err)
					c.AbortWithStatus(consts.StatusBadRequest)
					return
				}
				message, err = pack.MarshalWSMessage(&pack.WSMessage{
					Type: msg.Type,
					Data: messageList,
				})
				if err != nil {
					log.Println("failed to marshal ws message", err)
					c.AbortWithStatus(consts.StatusBadRequest)
					return
				}
			case pack.TypeGroupMessage:
				sendReq, err := pack.ParseSendRequest(msg.Data)
				if err != nil {
					log.Println("failed to parse send request:", err)
					c.AbortWithStatus(consts.StatusBadRequest)
					return
				}
				targetId, err := strconv.ParseInt(sendReq.TargetId, 10, 64)
				if err != nil {
					log.Println("failed to parse target id:", err)
					c.AbortWithStatus(consts.StatusBadRequest)
					return
				}
				err = rpc.SendMessageRPC(ctx, &chat.SendMessageRequest{
					SenderId: uid,
					TargetId: targetId,
					ChatType: chat.ChatType_CHAT_TYPE_GROUP,
					Content:  sendReq.Content,
				})
				if err != nil {
					log.Println("failed to send message:", err)
					c.AbortWithStatus(consts.StatusBadRequest)
					return
				}
				message, err = pack.MarshalWSMessage(&pack.WSMessage{
					Type: msg.Type,
					Data: "success",
				})
				if err != nil {
					log.Println("failed to marshal ws message", err)
					c.AbortWithStatus(consts.StatusBadRequest)
					return
				}
			case pack.TypeGroupHistory:
				historyReq, err := pack.ParseHistoryRequest(msg.Data)
				if err != nil {
					log.Println("failed to parse history request:", err)
					c.AbortWithStatus(consts.StatusBadRequest)
					return
				}
				targetId, err := strconv.ParseInt(historyReq.TargetId, 10, 64)
				if err != nil {
					log.Println("failed to parse target id:", err)
					c.AbortWithStatus(consts.StatusBadRequest)
					return
				}
				messageList, err := rpc.GetHistoryMessagesRPC(ctx, &chat.GetHistoryRequest{
					UserId:   uid,
					TargetId: targetId,
					ChatType: chat.ChatType_CHAT_TYPE_GROUP,
					Cursor:   historyReq.Cursor,
					Limit:    historyReq.Limit,
				})
				if err != nil {
					log.Println("failed to send message:", err)
					c.AbortWithStatus(consts.StatusBadRequest)
					return
				}
				message, err = pack.MarshalWSMessage(&pack.WSMessage{
					Type: msg.Type,
					Data: messageList,
				})
				if err != nil {
					log.Println("failed to marshal ws message", err)
					c.AbortWithStatus(consts.StatusBadRequest)
					return
				}
			default:
				log.Println("type is error")
				c.AbortWithStatus(consts.StatusBadRequest)
				return
			}
			err = conn.WriteMessage(mt, message)
			if err != nil {
				log.Println("failed to write return message:", err)
				c.AbortWithStatus(consts.StatusBadRequest)
				return
			}
		}
	})
	if err != nil {
		log.Print("upgrade:", err)
		c.AbortWithStatus(consts.StatusBadRequest)
		return
	}
}
