// Code generated by Kitex v0.15.2. DO NOT EDIT.

package video

import (
	"context"
	"myreel/kitex_gen/model"

	"github.com/cloudwego/prutal"
)

type Video struct {
	Id           int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Uid          int64  `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	CoverUrl     string `protobuf:"bytes,3,opt,name=coverUrl" json:"coverUrl,omitempty"`
	VideoUrl     string `protobuf:"bytes,4,opt,name=videoUrl" json:"videoUrl,omitempty"`
	Title        string `protobuf:"bytes,5,opt,name=title" json:"title,omitempty"`
	Description  string `protobuf:"bytes,6,opt,name=description" json:"description,omitempty"`
	VisitCount   *int64 `protobuf:"varint,7,opt,name=visitCount" json:"visitCount,omitempty"`
	LikeCount    *int64 `protobuf:"varint,8,opt,name=likeCount" json:"likeCount,omitempty"`
	CommentCount *int64 `protobuf:"varint,9,opt,name=commentCount" json:"commentCount,omitempty"`
}

func (x *Video) Reset() { *x = Video{} }

func (x *Video) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Video) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Video) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Video) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Video) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *Video) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *Video) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Video) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Video) GetVisitCount() int64 {
	if x != nil && x.VisitCount != nil {
		return *x.VisitCount
	}
	return 0
}

func (x *Video) GetLikeCount() int64 {
	if x != nil && x.LikeCount != nil {
		return *x.LikeCount
	}
	return 0
}

func (x *Video) GetCommentCount() int64 {
	if x != nil && x.CommentCount != nil {
		return *x.CommentCount
	}
	return 0
}

type VideoList struct {
	Items []*Video `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	Total *int64   `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
}

func (x *VideoList) Reset() { *x = VideoList{} }

func (x *VideoList) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *VideoList) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *VideoList) GetItems() []*Video {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *VideoList) GetTotal() int64 {
	if x != nil && x.Total != nil {
		return *x.Total
	}
	return 0
}

type VideoStreamRequest struct {
	LatestTime string `protobuf:"bytes,1,opt,name=latestTime" json:"latestTime,omitempty"`
}

func (x *VideoStreamRequest) Reset() { *x = VideoStreamRequest{} }

func (x *VideoStreamRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *VideoStreamRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *VideoStreamRequest) GetLatestTime() string {
	if x != nil {
		return x.LatestTime
	}
	return ""
}

type VideoStreamResponse struct {
	Base *model.BaseResp `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	Data *VideoList      `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (x *VideoStreamResponse) Reset() { *x = VideoStreamResponse{} }

func (x *VideoStreamResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *VideoStreamResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *VideoStreamResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *VideoStreamResponse) GetData() *VideoList {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetVideoUploadTokenRequest struct {
	Suffix string `protobuf:"bytes,1,opt,name=suffix" json:"suffix,omitempty"`
	UserId int64  `protobuf:"varint,2,opt,name=userId" json:"userId,omitempty"`
}

func (x *GetVideoUploadTokenRequest) Reset() { *x = GetVideoUploadTokenRequest{} }

func (x *GetVideoUploadTokenRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetVideoUploadTokenRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetVideoUploadTokenRequest) GetSuffix() string {
	if x != nil {
		return x.Suffix
	}
	return ""
}

func (x *GetVideoUploadTokenRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetVideoUploadTokenResponse struct {
	Base *model.BaseResp   `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	Data *model.UpyunToken `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (x *GetVideoUploadTokenResponse) Reset() { *x = GetVideoUploadTokenResponse{} }

func (x *GetVideoUploadTokenResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetVideoUploadTokenResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetVideoUploadTokenResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetVideoUploadTokenResponse) GetData() *model.UpyunToken {
	if x != nil {
		return x.Data
	}
	return nil
}

type PublishListRequest struct {
	Uid      string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	PageNum  int64  `protobuf:"varint,2,opt,name=pageNum" json:"pageNum,omitempty"`
	PageSize int64  `protobuf:"varint,3,opt,name=pageSize" json:"pageSize,omitempty"`
}

func (x *PublishListRequest) Reset() { *x = PublishListRequest{} }

func (x *PublishListRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PublishListRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PublishListRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PublishListRequest) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *PublishListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PublishListResponse struct {
	Base *model.BaseResp `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	Data *VideoList      `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (x *PublishListResponse) Reset() { *x = PublishListResponse{} }

func (x *PublishListResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PublishListResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PublishListResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *PublishListResponse) GetData() *VideoList {
	if x != nil {
		return x.Data
	}
	return nil
}

type PopularRequest struct {
	PageNum  int64 `protobuf:"varint,1,opt,name=pageNum" json:"pageNum,omitempty"`
	PageSize int64 `protobuf:"varint,2,opt,name=pageSize" json:"pageSize,omitempty"`
}

func (x *PopularRequest) Reset() { *x = PopularRequest{} }

func (x *PopularRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PopularRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PopularRequest) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *PopularRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PopularResponse struct {
	Base *model.BaseResp `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	Data *VideoList      `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (x *PopularResponse) Reset() { *x = PopularResponse{} }

func (x *PopularResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PopularResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PopularResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *PopularResponse) GetData() *VideoList {
	if x != nil {
		return x.Data
	}
	return nil
}

type SearchRequest struct {
	Keywords string `protobuf:"bytes,1,opt,name=keywords" json:"keywords,omitempty"`
	PageNum  int64  `protobuf:"varint,2,opt,name=pageNum" json:"pageNum,omitempty"`
	PageSize int64  `protobuf:"varint,3,opt,name=pageSize" json:"pageSize,omitempty"`
	FromDate string `protobuf:"bytes,4,opt,name=fromDate" json:"fromDate,omitempty"`
	ToDate   string `protobuf:"bytes,5,opt,name=toDate" json:"toDate,omitempty"`
	Username string `protobuf:"bytes,6,opt,name=username" json:"username,omitempty"`
}

func (x *SearchRequest) Reset() { *x = SearchRequest{} }

func (x *SearchRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SearchRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchRequest) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

func (x *SearchRequest) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *SearchRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchRequest) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *SearchRequest) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

func (x *SearchRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type SearchResponse struct {
	Base *model.BaseResp `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	Data *VideoList      `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (x *SearchResponse) Reset() { *x = SearchResponse{} }

func (x *SearchResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SearchResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *SearchResponse) GetData() *VideoList {
	if x != nil {
		return x.Data
	}
	return nil
}

type VideoService interface {
	VideoStream(ctx context.Context, req *VideoStreamRequest) (res *VideoStreamResponse, err error)
	GetVideoUploadToken(ctx context.Context, req *GetVideoUploadTokenRequest) (res *GetVideoUploadTokenResponse, err error)
	PublishList(ctx context.Context, req *PublishListRequest) (res *PublishListResponse, err error)
	Popular(ctx context.Context, req *PopularRequest) (res *PopularResponse, err error)
	Search(ctx context.Context, req *SearchRequest) (res *SearchResponse, err error)
}
