// Code generated by Kitex v0.15.2. DO NOT EDIT.

package chatservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	chat "myreel/kitex_gen/chat"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"SendMessage": kitex.NewMethodInfo(
		sendMessageHandler,
		newSendMessageArgs,
		newSendMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetHistory": kitex.NewMethodInfo(
		getHistoryHandler,
		newGetHistoryArgs,
		newGetHistoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetUnread": kitex.NewMethodInfo(
		getUnreadHandler,
		newGetUnreadArgs,
		newGetUnreadResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	chatServiceServiceInfo                = NewServiceInfo()
	chatServiceServiceInfoForClient       = NewServiceInfoForClient()
	chatServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return chatServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return chatServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return chatServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ChatService"
	handlerType := (*chat.ChatService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "chat",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func sendMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(chat.SendMessageRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(chat.ChatService).SendMessage(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SendMessageArgs:
		success, err := handler.(chat.ChatService).SendMessage(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SendMessageResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSendMessageArgs() interface{} {
	return &SendMessageArgs{}
}

func newSendMessageResult() interface{} {
	return &SendMessageResult{}
}

type SendMessageArgs struct {
	Req *chat.SendMessageRequest
}

func (p *SendMessageArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SendMessageArgs) Unmarshal(in []byte) error {
	msg := new(chat.SendMessageRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SendMessageArgs_Req_DEFAULT *chat.SendMessageRequest

func (p *SendMessageArgs) GetReq() *chat.SendMessageRequest {
	if !p.IsSetReq() {
		return SendMessageArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SendMessageArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SendMessageArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SendMessageResult struct {
	Success *chat.SendMessageResponse
}

var SendMessageResult_Success_DEFAULT *chat.SendMessageResponse

func (p *SendMessageResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SendMessageResult) Unmarshal(in []byte) error {
	msg := new(chat.SendMessageResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SendMessageResult) GetSuccess() *chat.SendMessageResponse {
	if !p.IsSetSuccess() {
		return SendMessageResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SendMessageResult) SetSuccess(x interface{}) {
	p.Success = x.(*chat.SendMessageResponse)
}

func (p *SendMessageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SendMessageResult) GetResult() interface{} {
	return p.Success
}

func getHistoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(chat.GetHistoryRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(chat.ChatService).GetHistory(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetHistoryArgs:
		success, err := handler.(chat.ChatService).GetHistory(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetHistoryResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetHistoryArgs() interface{} {
	return &GetHistoryArgs{}
}

func newGetHistoryResult() interface{} {
	return &GetHistoryResult{}
}

type GetHistoryArgs struct {
	Req *chat.GetHistoryRequest
}

func (p *GetHistoryArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetHistoryArgs) Unmarshal(in []byte) error {
	msg := new(chat.GetHistoryRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetHistoryArgs_Req_DEFAULT *chat.GetHistoryRequest

func (p *GetHistoryArgs) GetReq() *chat.GetHistoryRequest {
	if !p.IsSetReq() {
		return GetHistoryArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetHistoryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetHistoryArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetHistoryResult struct {
	Success *chat.GetHistoryResponse
}

var GetHistoryResult_Success_DEFAULT *chat.GetHistoryResponse

func (p *GetHistoryResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetHistoryResult) Unmarshal(in []byte) error {
	msg := new(chat.GetHistoryResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetHistoryResult) GetSuccess() *chat.GetHistoryResponse {
	if !p.IsSetSuccess() {
		return GetHistoryResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetHistoryResult) SetSuccess(x interface{}) {
	p.Success = x.(*chat.GetHistoryResponse)
}

func (p *GetHistoryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetHistoryResult) GetResult() interface{} {
	return p.Success
}

func getUnreadHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(chat.GetUnreadRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(chat.ChatService).GetUnread(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetUnreadArgs:
		success, err := handler.(chat.ChatService).GetUnread(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetUnreadResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetUnreadArgs() interface{} {
	return &GetUnreadArgs{}
}

func newGetUnreadResult() interface{} {
	return &GetUnreadResult{}
}

type GetUnreadArgs struct {
	Req *chat.GetUnreadRequest
}

func (p *GetUnreadArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetUnreadArgs) Unmarshal(in []byte) error {
	msg := new(chat.GetUnreadRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetUnreadArgs_Req_DEFAULT *chat.GetUnreadRequest

func (p *GetUnreadArgs) GetReq() *chat.GetUnreadRequest {
	if !p.IsSetReq() {
		return GetUnreadArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetUnreadArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetUnreadArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetUnreadResult struct {
	Success *chat.GetUnreadResponse
}

var GetUnreadResult_Success_DEFAULT *chat.GetUnreadResponse

func (p *GetUnreadResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetUnreadResult) Unmarshal(in []byte) error {
	msg := new(chat.GetUnreadResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetUnreadResult) GetSuccess() *chat.GetUnreadResponse {
	if !p.IsSetSuccess() {
		return GetUnreadResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetUnreadResult) SetSuccess(x interface{}) {
	p.Success = x.(*chat.GetUnreadResponse)
}

func (p *GetUnreadResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetUnreadResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) SendMessage(ctx context.Context, Req *chat.SendMessageRequest) (r *chat.SendMessageResponse, err error) {
	var _args SendMessageArgs
	_args.Req = Req
	var _result SendMessageResult
	if err = p.c.Call(ctx, "SendMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetHistory(ctx context.Context, Req *chat.GetHistoryRequest) (r *chat.GetHistoryResponse, err error) {
	var _args GetHistoryArgs
	_args.Req = Req
	var _result GetHistoryResult
	if err = p.c.Call(ctx, "GetHistory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUnread(ctx context.Context, Req *chat.GetUnreadRequest) (r *chat.GetUnreadResponse, err error) {
	var _args GetUnreadArgs
	_args.Req = Req
	var _result GetUnreadResult
	if err = p.c.Call(ctx, "GetUnread", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
