// Code generated by Kitex v0.15.2. DO NOT EDIT.

package chatservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	chat "myreel/kitex_gen/chat"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SendMessage(ctx context.Context, Req *chat.SendMessageRequest, callOptions ...callopt.Option) (r *chat.SendMessageResponse, err error)
	GetHistory(ctx context.Context, Req *chat.GetHistoryRequest, callOptions ...callopt.Option) (r *chat.GetHistoryResponse, err error)
	GetUnread(ctx context.Context, Req *chat.GetUnreadRequest, callOptions ...callopt.Option) (r *chat.GetUnreadResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kChatServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kChatServiceClient struct {
	*kClient
}

func (p *kChatServiceClient) SendMessage(ctx context.Context, Req *chat.SendMessageRequest, callOptions ...callopt.Option) (r *chat.SendMessageResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendMessage(ctx, Req)
}

func (p *kChatServiceClient) GetHistory(ctx context.Context, Req *chat.GetHistoryRequest, callOptions ...callopt.Option) (r *chat.GetHistoryResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetHistory(ctx, Req)
}

func (p *kChatServiceClient) GetUnread(ctx context.Context, Req *chat.GetUnreadRequest, callOptions ...callopt.Option) (r *chat.GetUnreadResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUnread(ctx, Req)
}
