// Code generated by Kitex v0.15.2. DO NOT EDIT.

package follow

import (
	"context"
	"myreel/kitex_gen/model"

	"github.com/cloudwego/prutal"
)

type User struct {
	Id        int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Username  string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	AvatarUrl string `protobuf:"bytes,3,opt,name=avatarUrl" json:"avatarUrl,omitempty"`
}

func (x *User) Reset() { *x = User{} }

func (x *User) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *User) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type Group struct {
	Id        int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	CreatorId int64  `protobuf:"varint,3,opt,name=creatorId" json:"creatorId,omitempty"`
	CreatedAt int64  `protobuf:"varint,4,opt,name=createdAt" json:"createdAt,omitempty"`
}

func (x *Group) Reset() { *x = Group{} }

func (x *Group) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Group) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Group) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *Group) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type Pagination struct {
	NextCursor int64 `protobuf:"varint,1,opt,name=nextCursor" json:"nextCursor,omitempty"`
	PrevCursor int64 `protobuf:"varint,2,opt,name=prevCursor" json:"prevCursor,omitempty"`
	Total      int64 `protobuf:"varint,3,opt,name=total" json:"total,omitempty"`
}

func (x *Pagination) Reset() { *x = Pagination{} }

func (x *Pagination) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Pagination) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Pagination) GetNextCursor() int64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

func (x *Pagination) GetPrevCursor() int64 {
	if x != nil {
		return x.PrevCursor
	}
	return 0
}

func (x *Pagination) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UserList struct {
	Items      []*User     `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	Pagination *Pagination `protobuf:"bytes,2,opt,name=pagination" json:"pagination,omitempty"`
}

func (x *UserList) Reset() { *x = UserList{} }

func (x *UserList) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserList) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserList) GetItems() []*User {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *UserList) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GroupList struct {
	Items []*Group `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (x *GroupList) Reset() { *x = GroupList{} }

func (x *GroupList) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GroupList) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GroupList) GetItems() []*Group {
	if x != nil {
		return x.Items
	}
	return nil
}

type FollowActionRequest struct {
	ToUserId   int64 `protobuf:"varint,1,opt,name=toUserId" json:"toUserId,omitempty"`
	ActionType int64 `protobuf:"varint,2,opt,name=actionType" json:"actionType,omitempty"`
	UserId     int64 `protobuf:"varint,3,opt,name=userId" json:"userId,omitempty"`
}

func (x *FollowActionRequest) Reset() { *x = FollowActionRequest{} }

func (x *FollowActionRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *FollowActionRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FollowActionRequest) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *FollowActionRequest) GetActionType() int64 {
	if x != nil {
		return x.ActionType
	}
	return 0
}

func (x *FollowActionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type FollowActionResponse struct {
	Base *model.BaseResp `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
}

func (x *FollowActionResponse) Reset() { *x = FollowActionResponse{} }

func (x *FollowActionResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *FollowActionResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FollowActionResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

type FolloweringListRequest struct {
	UserId int64 `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	Cursor int64 `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"`
	Limit  int64 `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
}

func (x *FolloweringListRequest) Reset() { *x = FolloweringListRequest{} }

func (x *FolloweringListRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *FolloweringListRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FolloweringListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FolloweringListRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *FolloweringListRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FolloweringListResponse struct {
	Base *model.BaseResp `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	Data *UserList       `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (x *FolloweringListResponse) Reset() { *x = FolloweringListResponse{} }

func (x *FolloweringListResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *FolloweringListResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FolloweringListResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *FolloweringListResponse) GetData() *UserList {
	if x != nil {
		return x.Data
	}
	return nil
}

type FolloweredListRequest struct {
	UserId int64 `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	Cursor int64 `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"`
	Limit  int64 `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
}

func (x *FolloweredListRequest) Reset() { *x = FolloweredListRequest{} }

func (x *FolloweredListRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *FolloweredListRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FolloweredListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FolloweredListRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *FolloweredListRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FolloweredListResponse struct {
	Base *model.BaseResp `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	Data *UserList       `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (x *FolloweredListResponse) Reset() { *x = FolloweredListResponse{} }

func (x *FolloweredListResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *FolloweredListResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FolloweredListResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *FolloweredListResponse) GetData() *UserList {
	if x != nil {
		return x.Data
	}
	return nil
}

type FriendListRequest struct {
	UserId int64 `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	Cursor int64 `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"`
	Limit  int64 `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
}

func (x *FriendListRequest) Reset() { *x = FriendListRequest{} }

func (x *FriendListRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *FriendListRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FriendListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FriendListRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *FriendListRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FriendListResponse struct {
	Base *model.BaseResp `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	Data *UserList       `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (x *FriendListResponse) Reset() { *x = FriendListResponse{} }

func (x *FriendListResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *FriendListResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FriendListResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *FriendListResponse) GetData() *UserList {
	if x != nil {
		return x.Data
	}
	return nil
}

type ChatGroupRequest struct {
	UserId    int64   `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	Name      string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	FriendIds []int64 `protobuf:"varint,3,rep,packed,name=friend_ids" json:"friend_ids,omitempty"`
}

func (x *ChatGroupRequest) Reset() { *x = ChatGroupRequest{} }

func (x *ChatGroupRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ChatGroupRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ChatGroupRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChatGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatGroupRequest) GetFriendIds() []int64 {
	if x != nil {
		return x.FriendIds
	}
	return nil
}

type ChatGroupResponse struct {
	Base *model.BaseResp `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
}

func (x *ChatGroupResponse) Reset() { *x = ChatGroupResponse{} }

func (x *ChatGroupResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ChatGroupResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ChatGroupResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

type JoinedChatGroupListRequest struct {
	UserId int64 `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
}

func (x *JoinedChatGroupListRequest) Reset() { *x = JoinedChatGroupListRequest{} }

func (x *JoinedChatGroupListRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *JoinedChatGroupListRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *JoinedChatGroupListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type JoinedChatGroupListResponse struct {
	Base *model.BaseResp `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	Data *GroupList      `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (x *JoinedChatGroupListResponse) Reset() { *x = JoinedChatGroupListResponse{} }

func (x *JoinedChatGroupListResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *JoinedChatGroupListResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *JoinedChatGroupListResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *JoinedChatGroupListResponse) GetData() *GroupList {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreatedChatGroupListRequest struct {
	UserId int64 `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
}

func (x *CreatedChatGroupListRequest) Reset() { *x = CreatedChatGroupListRequest{} }

func (x *CreatedChatGroupListRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *CreatedChatGroupListRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreatedChatGroupListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreatedChatGroupListResponse struct {
	Base *model.BaseResp `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	Data *GroupList      `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (x *CreatedChatGroupListResponse) Reset() { *x = CreatedChatGroupListResponse{} }

func (x *CreatedChatGroupListResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *CreatedChatGroupListResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreatedChatGroupListResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *CreatedChatGroupListResponse) GetData() *GroupList {
	if x != nil {
		return x.Data
	}
	return nil
}

type FollowService interface {
	FollowAction(ctx context.Context, req *FollowActionRequest) (res *FollowActionResponse, err error)
	FolloweringList(ctx context.Context, req *FolloweringListRequest) (res *FolloweringListResponse, err error)
	FolloweredList(ctx context.Context, req *FolloweredListRequest) (res *FolloweredListResponse, err error)
	FriendList(ctx context.Context, req *FriendListRequest) (res *FriendListResponse, err error)
	ChatGroup(ctx context.Context, req *ChatGroupRequest) (res *ChatGroupResponse, err error)
	JoinedChatGroupList(ctx context.Context, req *JoinedChatGroupListRequest) (res *JoinedChatGroupListResponse, err error)
	CreatedChatGroupList(ctx context.Context, req *CreatedChatGroupListRequest) (res *CreatedChatGroupListResponse, err error)
}
