// Code generated by Kitex v0.15.2. DO NOT EDIT.

package comment

import (
	"context"
	"myreel/kitex_gen/model"

	"github.com/cloudwego/prutal"
)

type Comment struct {
	Id         int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Uid        int64  `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	VideoId    int64  `protobuf:"varint,3,opt,name=videoId" json:"videoId,omitempty"`
	ParentId   int64  `protobuf:"varint,4,opt,name=parentId" json:"parentId,omitempty"`
	LikeCount  *int64 `protobuf:"varint,5,opt,name=likeCount" json:"likeCount,omitempty"`
	ChildCount *int64 `protobuf:"varint,6,opt,name=childCount" json:"childCount,omitempty"`
	Content    string `protobuf:"bytes,7,opt,name=content" json:"content,omitempty"`
	CreatedAt  int64  `protobuf:"varint,8,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt  int64  `protobuf:"varint,9,opt,name=updatedAt" json:"updatedAt,omitempty"`
}

func (x *Comment) Reset() { *x = Comment{} }

func (x *Comment) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Comment) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Comment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comment) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Comment) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *Comment) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Comment) GetLikeCount() int64 {
	if x != nil && x.LikeCount != nil {
		return *x.LikeCount
	}
	return 0
}

func (x *Comment) GetChildCount() int64 {
	if x != nil && x.ChildCount != nil {
		return *x.ChildCount
	}
	return 0
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Comment) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type Pagination struct {
	NextCursor int64 `protobuf:"varint,1,opt,name=nextCursor" json:"nextCursor,omitempty"`
	PrevCursor int64 `protobuf:"varint,2,opt,name=prevCursor" json:"prevCursor,omitempty"`
	Total      int64 `protobuf:"varint,3,opt,name=total" json:"total,omitempty"`
}

func (x *Pagination) Reset() { *x = Pagination{} }

func (x *Pagination) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Pagination) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Pagination) GetNextCursor() int64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

func (x *Pagination) GetPrevCursor() int64 {
	if x != nil {
		return x.PrevCursor
	}
	return 0
}

func (x *Pagination) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CommentList struct {
	Items      []*Comment  `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	Pagination *Pagination `protobuf:"bytes,2,opt,name=pagination" json:"pagination,omitempty"`
}

func (x *CommentList) Reset() { *x = CommentList{} }

func (x *CommentList) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CommentList) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CommentList) GetItems() []*Comment {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CommentList) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type CommentPublishRequest struct {
	VideoId   int64  `protobuf:"varint,1,opt,name=videoId" json:"videoId,omitempty"`
	CommentId int64  `protobuf:"varint,2,opt,name=commentId" json:"commentId,omitempty"`
	Content   string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
	UserId    int64  `protobuf:"varint,4,opt,name=userId" json:"userId,omitempty"`
}

func (x *CommentPublishRequest) Reset() { *x = CommentPublishRequest{} }

func (x *CommentPublishRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *CommentPublishRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CommentPublishRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *CommentPublishRequest) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *CommentPublishRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentPublishRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CommentPublishResponse struct {
	Base *model.BaseResp `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
}

func (x *CommentPublishResponse) Reset() { *x = CommentPublishResponse{} }

func (x *CommentPublishResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *CommentPublishResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CommentPublishResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

type CommentListRequest struct {
	VideoId   int64 `protobuf:"varint,1,opt,name=videoId" json:"videoId,omitempty"`
	CommentId int64 `protobuf:"varint,2,opt,name=commentId" json:"commentId,omitempty"`
	Cursor    int64 `protobuf:"varint,3,opt,name=cursor" json:"cursor,omitempty"`
	Limit     int64 `protobuf:"varint,4,opt,name=limit" json:"limit,omitempty"`
}

func (x *CommentListRequest) Reset() { *x = CommentListRequest{} }

func (x *CommentListRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CommentListRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CommentListRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *CommentListRequest) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *CommentListRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *CommentListRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CommentListResponse struct {
	Base *model.BaseResp `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	Data *CommentList    `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (x *CommentListResponse) Reset() { *x = CommentListResponse{} }

func (x *CommentListResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CommentListResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CommentListResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *CommentListResponse) GetData() *CommentList {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteRequest struct {
	VideoId   int64 `protobuf:"varint,1,opt,name=videoId" json:"videoId,omitempty"`
	CommentId int64 `protobuf:"varint,2,opt,name=commentId" json:"commentId,omitempty"`
	UserId    int64 `protobuf:"varint,3,opt,name=userId" json:"userId,omitempty"`
}

func (x *DeleteRequest) Reset() { *x = DeleteRequest{} }

func (x *DeleteRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *DeleteRequest) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *DeleteRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteResponse struct {
	Base *model.BaseResp `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
}

func (x *DeleteResponse) Reset() { *x = DeleteResponse{} }

func (x *DeleteResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

type CommentService interface {
	CommentPublish(ctx context.Context, req *CommentPublishRequest) (res *CommentPublishResponse, err error)
	CommentList(ctx context.Context, req *CommentListRequest) (res *CommentListResponse, err error)
	Delete(ctx context.Context, req *DeleteRequest) (res *DeleteResponse, err error)
}
