// Code generated by Kitex v0.15.2. DO NOT EDIT.

package commentservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	comment "myreel/kitex_gen/comment"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CommentPublish(ctx context.Context, Req *comment.CommentPublishRequest, callOptions ...callopt.Option) (r *comment.CommentPublishResponse, err error)
	CommentList(ctx context.Context, Req *comment.CommentListRequest, callOptions ...callopt.Option) (r *comment.CommentListResponse, err error)
	Delete(ctx context.Context, Req *comment.DeleteRequest, callOptions ...callopt.Option) (r *comment.DeleteResponse, err error)
	CommentLikeAction(ctx context.Context, Req *comment.CommentLikeActionRequest, callOptions ...callopt.Option) (r *comment.CommentLikeActionResonse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kCommentServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCommentServiceClient struct {
	*kClient
}

func (p *kCommentServiceClient) CommentPublish(ctx context.Context, Req *comment.CommentPublishRequest, callOptions ...callopt.Option) (r *comment.CommentPublishResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentPublish(ctx, Req)
}

func (p *kCommentServiceClient) CommentList(ctx context.Context, Req *comment.CommentListRequest, callOptions ...callopt.Option) (r *comment.CommentListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentList(ctx, Req)
}

func (p *kCommentServiceClient) Delete(ctx context.Context, Req *comment.DeleteRequest, callOptions ...callopt.Option) (r *comment.DeleteResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Delete(ctx, Req)
}

func (p *kCommentServiceClient) CommentLikeAction(ctx context.Context, Req *comment.CommentLikeActionRequest, callOptions ...callopt.Option) (r *comment.CommentLikeActionResonse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentLikeAction(ctx, Req)
}
