// Code generated by Kitex v0.15.2. DO NOT EDIT.

package commentservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	comment "myreel/kitex_gen/comment"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CommentPublish": kitex.NewMethodInfo(
		commentPublishHandler,
		newCommentPublishArgs,
		newCommentPublishResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CommentList": kitex.NewMethodInfo(
		commentListHandler,
		newCommentListArgs,
		newCommentListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Delete": kitex.NewMethodInfo(
		deleteHandler,
		newDeleteArgs,
		newDeleteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CommentLikeAction": kitex.NewMethodInfo(
		commentLikeActionHandler,
		newCommentLikeActionArgs,
		newCommentLikeActionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	commentServiceServiceInfo                = NewServiceInfo()
	commentServiceServiceInfoForClient       = NewServiceInfoForClient()
	commentServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return commentServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return commentServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return commentServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "CommentService"
	handlerType := (*comment.CommentService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "comment",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func commentPublishHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(comment.CommentPublishRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(comment.CommentService).CommentPublish(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CommentPublishArgs:
		success, err := handler.(comment.CommentService).CommentPublish(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CommentPublishResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCommentPublishArgs() interface{} {
	return &CommentPublishArgs{}
}

func newCommentPublishResult() interface{} {
	return &CommentPublishResult{}
}

type CommentPublishArgs struct {
	Req *comment.CommentPublishRequest
}

func (p *CommentPublishArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CommentPublishArgs) Unmarshal(in []byte) error {
	msg := new(comment.CommentPublishRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CommentPublishArgs_Req_DEFAULT *comment.CommentPublishRequest

func (p *CommentPublishArgs) GetReq() *comment.CommentPublishRequest {
	if !p.IsSetReq() {
		return CommentPublishArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CommentPublishArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CommentPublishArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CommentPublishResult struct {
	Success *comment.CommentPublishResponse
}

var CommentPublishResult_Success_DEFAULT *comment.CommentPublishResponse

func (p *CommentPublishResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CommentPublishResult) Unmarshal(in []byte) error {
	msg := new(comment.CommentPublishResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CommentPublishResult) GetSuccess() *comment.CommentPublishResponse {
	if !p.IsSetSuccess() {
		return CommentPublishResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CommentPublishResult) SetSuccess(x interface{}) {
	p.Success = x.(*comment.CommentPublishResponse)
}

func (p *CommentPublishResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CommentPublishResult) GetResult() interface{} {
	return p.Success
}

func commentListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(comment.CommentListRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(comment.CommentService).CommentList(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CommentListArgs:
		success, err := handler.(comment.CommentService).CommentList(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CommentListResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCommentListArgs() interface{} {
	return &CommentListArgs{}
}

func newCommentListResult() interface{} {
	return &CommentListResult{}
}

type CommentListArgs struct {
	Req *comment.CommentListRequest
}

func (p *CommentListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CommentListArgs) Unmarshal(in []byte) error {
	msg := new(comment.CommentListRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CommentListArgs_Req_DEFAULT *comment.CommentListRequest

func (p *CommentListArgs) GetReq() *comment.CommentListRequest {
	if !p.IsSetReq() {
		return CommentListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CommentListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CommentListArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CommentListResult struct {
	Success *comment.CommentListResponse
}

var CommentListResult_Success_DEFAULT *comment.CommentListResponse

func (p *CommentListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CommentListResult) Unmarshal(in []byte) error {
	msg := new(comment.CommentListResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CommentListResult) GetSuccess() *comment.CommentListResponse {
	if !p.IsSetSuccess() {
		return CommentListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CommentListResult) SetSuccess(x interface{}) {
	p.Success = x.(*comment.CommentListResponse)
}

func (p *CommentListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CommentListResult) GetResult() interface{} {
	return p.Success
}

func deleteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(comment.DeleteRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(comment.CommentService).Delete(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DeleteArgs:
		success, err := handler.(comment.CommentService).Delete(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeleteResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDeleteArgs() interface{} {
	return &DeleteArgs{}
}

func newDeleteResult() interface{} {
	return &DeleteResult{}
}

type DeleteArgs struct {
	Req *comment.DeleteRequest
}

func (p *DeleteArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeleteArgs) Unmarshal(in []byte) error {
	msg := new(comment.DeleteRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeleteArgs_Req_DEFAULT *comment.DeleteRequest

func (p *DeleteArgs) GetReq() *comment.DeleteRequest {
	if !p.IsSetReq() {
		return DeleteArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeleteArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeleteArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeleteResult struct {
	Success *comment.DeleteResponse
}

var DeleteResult_Success_DEFAULT *comment.DeleteResponse

func (p *DeleteResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeleteResult) Unmarshal(in []byte) error {
	msg := new(comment.DeleteResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeleteResult) GetSuccess() *comment.DeleteResponse {
	if !p.IsSetSuccess() {
		return DeleteResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeleteResult) SetSuccess(x interface{}) {
	p.Success = x.(*comment.DeleteResponse)
}

func (p *DeleteResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeleteResult) GetResult() interface{} {
	return p.Success
}

func commentLikeActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(comment.CommentLikeActionRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(comment.CommentService).CommentLikeAction(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CommentLikeActionArgs:
		success, err := handler.(comment.CommentService).CommentLikeAction(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CommentLikeActionResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCommentLikeActionArgs() interface{} {
	return &CommentLikeActionArgs{}
}

func newCommentLikeActionResult() interface{} {
	return &CommentLikeActionResult{}
}

type CommentLikeActionArgs struct {
	Req *comment.CommentLikeActionRequest
}

func (p *CommentLikeActionArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CommentLikeActionArgs) Unmarshal(in []byte) error {
	msg := new(comment.CommentLikeActionRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CommentLikeActionArgs_Req_DEFAULT *comment.CommentLikeActionRequest

func (p *CommentLikeActionArgs) GetReq() *comment.CommentLikeActionRequest {
	if !p.IsSetReq() {
		return CommentLikeActionArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CommentLikeActionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CommentLikeActionArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CommentLikeActionResult struct {
	Success *comment.CommentLikeActionResonse
}

var CommentLikeActionResult_Success_DEFAULT *comment.CommentLikeActionResonse

func (p *CommentLikeActionResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CommentLikeActionResult) Unmarshal(in []byte) error {
	msg := new(comment.CommentLikeActionResonse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CommentLikeActionResult) GetSuccess() *comment.CommentLikeActionResonse {
	if !p.IsSetSuccess() {
		return CommentLikeActionResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CommentLikeActionResult) SetSuccess(x interface{}) {
	p.Success = x.(*comment.CommentLikeActionResonse)
}

func (p *CommentLikeActionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CommentLikeActionResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CommentPublish(ctx context.Context, Req *comment.CommentPublishRequest) (r *comment.CommentPublishResponse, err error) {
	var _args CommentPublishArgs
	_args.Req = Req
	var _result CommentPublishResult
	if err = p.c.Call(ctx, "CommentPublish", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CommentList(ctx context.Context, Req *comment.CommentListRequest) (r *comment.CommentListResponse, err error) {
	var _args CommentListArgs
	_args.Req = Req
	var _result CommentListResult
	if err = p.c.Call(ctx, "CommentList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Delete(ctx context.Context, Req *comment.DeleteRequest) (r *comment.DeleteResponse, err error) {
	var _args DeleteArgs
	_args.Req = Req
	var _result DeleteResult
	if err = p.c.Call(ctx, "Delete", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CommentLikeAction(ctx context.Context, Req *comment.CommentLikeActionRequest) (r *comment.CommentLikeActionResonse, err error) {
	var _args CommentLikeActionArgs
	_args.Req = Req
	var _result CommentLikeActionResult
	if err = p.c.Call(ctx, "CommentLikeAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
