// Code generated by hertz generator.

package comment

import (
	"myreel/app/gateway/mv"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		mv.Auth(),
	}
}

func _commentlistMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		mv.Auth(),
	}
}

func _commentpublishMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		mv.Auth(),
	}
}
