// Code generated by hertz generator.

package video

import (
	"myreel/app/gateway/mv"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videostreamMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		mv.Auth(),
	}
}

func _publishlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _popularMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getvideouploadtokenMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		mv.Auth(),
	}
}
