// Code generated by hertz generator.

package user

import (
	"context"
	"strconv"

	api "myreel/app/gateway/model/api/user"
	"myreel/app/gateway/pack"
	"myreel/app/gateway/rpc"
	"myreel/kitex_gen/user"
	"myreel/pkg/constants"
	"myreel/pkg/errno"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Login .
// @router /user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.LoginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamVerifyError.WithError(err))
		return
	}

	data, err := rpc.LoginRPC(ctx, &user.LoginRequest{
		Username: req.Username,
		Password: req.Password,
		Code:     req.Code,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespData(c, data)
}

// Register .
// @router /user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.RegisterRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamVerifyError.WithError(err))
		return
	}

	err = rpc.RegisterRPC(ctx, &user.RegisterRequest{
		Username: req.Username,
		Password: req.Password,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespSuccess(c)
}

// GetUserInfo .
// @router /user/info [GET]
func GetUserInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetUserInfoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamVerifyError.WithError(err))
		return
	}

	data, err := rpc.GetUserByIdRPC(ctx, &user.GetUserInfoRequest{
		UserId: req.UserId,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespData(c, data)
}

// GetMFA .
// @router /user/mfa/qrcode [GET]
func GetMFA(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetMFARequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.GetMFAResponse)

	c.JSON(consts.StatusOK, resp)
}

// BindMFA .
// @router user/mfa/bind [POST]
func BindMFA(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.BindMFARequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.BindMFAResponse)

	c.JSON(consts.StatusOK, resp)
}

// SearchImg .
// @router /user/image/search [POST]
func SearchImg(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.SearchImgRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.SearchImgResponse)

	c.JSON(consts.StatusOK, resp)
}

// Refresh .
// @router /refresh [GET]
func Refresh(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.RefreshRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamVerifyError.WithError(err))
		return
	}

	token := string(c.GetHeader(constants.AuthHeader))
	val, exist := c.Get(constants.CtxUserIdKey)
	if !exist {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}
	uid, ok := val.(int64)
	if !ok {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}

	data, err := rpc.RefreshRPC(ctx, &user.RefreshRequest{
		Token:  token,
		UserId: uid,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespData(c, data)
}

// GetUploadToken .
// @router /api/v1/user/avatar/token [PUT]
func GetUploadToken(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetUploadTokenRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamVerifyError.WithError(err))
		return
	}

	val, exist := c.Get(constants.CtxUserIdKey)
	if !exist {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}
	uid, ok := val.(int64)
	if !ok {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}

	data, err := rpc.GetUploadTokenRPC(ctx, &user.GetUploadTokenRequest{
		Suffix: req.Suffix,
		UserId: uid,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespData(c, data)
}

// AvatarNotify .
// @router /api/v1/user/avatar/notify [POST]
func AvatarNotify(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.AvatarNotifyRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespData(c, "fail")
		return
	}

	if req.Code != constants.UpyunNotifySuccess {
		pack.RespData(c, "fail")
		return
	}

	pack.RespSuccess(c)

	uid, err := strconv.ParseInt(req.Uid, 10, 64)
	if err != nil {
		pack.RespData(c, "fail")
		return
	}

	rpc.SetUseravatarRPC(ctx, &user.SetUserAvatarUrlRequest{
		UserId: uid,
		Url:    req.Url,
	})
}
