// Code generated by hertz generator.

package comment

import (
	"context"
	api "myreel/app/gateway/model/api/comment"
	"myreel/app/gateway/pack"
	"myreel/app/gateway/rpc"
	"myreel/kitex_gen/comment"
	"myreel/pkg/constants"
	"myreel/pkg/errno"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// CommentPublish .
// @router /api/v1/comment/publish [POST]
func CommentPublish(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.CommentPublishRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamVerifyError.WithError(err))
		return
	}

	val, exist := c.Get(constants.CtxUserIdKey)
	if !exist {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}
	uid, ok := val.(int64)
	if !ok {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}

	err = rpc.CommentPublishRPC(ctx, &comment.CommentPublishRequest{
		VideoId:   req.VideoId,
		CommentId: req.CommentId,
		Content:   req.Content,
		UserId:    uid,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespSuccess(c)
}

// CommentList .
// @router /api/v1/comment/list [GET]
func CommentList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.CommentListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamVerifyError.WithError(err))
		return
	}

	data, err := rpc.GetCommentList(ctx, &comment.CommentListRequest{
		VideoId:   req.VideoId,
		CommentId: req.CommentId,
		Cursor:    req.Cursor,
		Limit:     req.Limit,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespData(c, data)
}

// Delete .
// @router /api/v1/comment/delete [DELETE]
func Delete(ctx context.Context, c *app.RequestContext) {
	var err error
	var req comment.DeleteRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(comment.DeleteResponse)

	c.JSON(consts.StatusOK, resp)
}
