// Code generated by hertz generator.

package follow

import (
	"context"

	api "myreel/app/gateway/model/api/follow"
	"myreel/app/gateway/pack"
	"myreel/app/gateway/rpc"
	"myreel/kitex_gen/follow"
	"myreel/pkg/constants"
	"myreel/pkg/errno"

	"github.com/cloudwego/hertz/pkg/app"
)

// FollowAction .
// @router /api/v1/relation/action [POST]
func FollowAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.FollowActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamVerifyError.WithError(err))
		return
	}

	val, exist := c.Get(constants.CtxUserIdKey)
	if !exist {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}
	uid, ok := val.(int64)
	if !ok {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}

	err = rpc.FollowActionRPC(ctx, &follow.FollowActionRequest{
		ToUserId:   req.ToUserId,
		ActionType: req.ActionType,
		UserId:     uid,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespSuccess(c)
}

// FolloweredList .
// @router /api/v1/followered/list [GET]
func FolloweredList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.FolloweredListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamVerifyError.WithError(err))
		return
	}

	val, exist := c.Get(constants.CtxUserIdKey)
	if !exist {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}
	uid, ok := val.(int64)
	if !ok {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}

	data, err := rpc.GetFolloweredsByIdsRPC(ctx, &follow.FolloweredListRequest{
		UserId: uid,
		Cursor: req.Cursor,
		Limit:  req.Limit,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespData(c, data)
}

// FriendList .
// @router /api/v1/friends/list [GET]
func FriendList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.FriendListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamVerifyError.WithError(err))
		return
	}

	val, exist := c.Get(constants.CtxUserIdKey)
	if !exist {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}
	uid, ok := val.(int64)
	if !ok {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}

	data, err := rpc.GetFriendsByIdRPC(ctx, &follow.FriendListRequest{
		UserId: uid,
		Cursor: req.Cursor,
		Limit:  req.Limit,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespData(c, data)
}

// FolloweringList .
// @router /api/v1/following/list [GET]
func FolloweringList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.FolloweringListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamVerifyError.WithError(err))
		return
	}

	val, exist := c.Get(constants.CtxUserIdKey)
	if !exist {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}
	uid, ok := val.(int64)
	if !ok {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}

	data, err := rpc.GetFolloweringsByIdsRPC(ctx, &follow.FolloweringListRequest{
		UserId: uid,
		Cursor: req.Cursor,
		Limit:  req.Limit,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespData(c, data)
}

// ChatGroup .
// @router /api/v1/friends/group [POST]
func ChatGroup(ctx context.Context, c *app.RequestContext) {
	var err error
	var req follow.ChatGroupRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamVerifyError.WithError(err))
		return
	}

	val, exist := c.Get(constants.CtxUserIdKey)
	if !exist {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}
	uid, ok := val.(int64)
	if !ok {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}

	err = rpc.CreateGroupRPC(ctx, &follow.ChatGroupRequest{
		UserId:    uid,
		Name:      req.Name,
		FriendIds: req.FriendIds,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespSuccess(c)
}

// JoinedChatGroupList .
// @router /api/v1/friends/group/joined [GET]
func JoinedChatGroupList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req follow.JoinedChatGroupListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamVerifyError.WithError(err))
		return
	}

	val, exist := c.Get(constants.CtxUserIdKey)
	if !exist {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}
	uid, ok := val.(int64)
	if !ok {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}

	data, err := rpc.GetGroupByJoinedRPC(ctx, &follow.JoinedChatGroupListRequest{
		UserId: uid,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespData(c, data)
}

// CreatedChatGroupList .
// @router /api/v1/friends/group/created [GET]
func CreatedChatGroupList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req follow.CreatedChatGroupListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamVerifyError.WithError(err))
		return
	}

	val, exist := c.Get(constants.CtxUserIdKey)
	if !exist {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}
	uid, ok := val.(int64)
	if !ok {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}

	data, err := rpc.GetGroupByCreatedRPC(ctx, &follow.CreatedChatGroupListRequest{
		UserId: uid,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespData(c, data)
}
