// Code generated by hertz generator.

package like

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likeactionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likelistMw() []app.HandlerFunc {
	// your code...
	return nil
}
