// Code generated by hertz generator.

package like

import (
	"myreel/app/gateway/mv"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likeactionMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		mv.Auth(),
	}
}

func _likelistMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		mv.Auth(),
	}
}
