// Code generated by Kitex v0.15.2. DO NOT EDIT.

package followservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	follow "myreel/kitex_gen/follow"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	FollowAction(ctx context.Context, Req *follow.FollowActionRequest, callOptions ...callopt.Option) (r *follow.FollowActionResponse, err error)
	FolloweringList(ctx context.Context, Req *follow.FolloweringListRequest, callOptions ...callopt.Option) (r *follow.FolloweringListResponse, err error)
	FolloweredList(ctx context.Context, Req *follow.FolloweredListRequest, callOptions ...callopt.Option) (r *follow.FolloweredListResponse, err error)
	FriendList(ctx context.Context, Req *follow.FriendListRequest, callOptions ...callopt.Option) (r *follow.FriendListResponse, err error)
	ChatGroup(ctx context.Context, Req *follow.ChatGroupRequest, callOptions ...callopt.Option) (r *follow.ChatGroupResponse, err error)
	JoinedChatGroupList(ctx context.Context, Req *follow.JoinedChatGroupListRequest, callOptions ...callopt.Option) (r *follow.JoinedChatGroupListResponse, err error)
	CreatedChatGroupList(ctx context.Context, Req *follow.CreatedChatGroupListRequest, callOptions ...callopt.Option) (r *follow.CreatedChatGroupListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kFollowServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kFollowServiceClient struct {
	*kClient
}

func (p *kFollowServiceClient) FollowAction(ctx context.Context, Req *follow.FollowActionRequest, callOptions ...callopt.Option) (r *follow.FollowActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowAction(ctx, Req)
}

func (p *kFollowServiceClient) FolloweringList(ctx context.Context, Req *follow.FolloweringListRequest, callOptions ...callopt.Option) (r *follow.FolloweringListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FolloweringList(ctx, Req)
}

func (p *kFollowServiceClient) FolloweredList(ctx context.Context, Req *follow.FolloweredListRequest, callOptions ...callopt.Option) (r *follow.FolloweredListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FolloweredList(ctx, Req)
}

func (p *kFollowServiceClient) FriendList(ctx context.Context, Req *follow.FriendListRequest, callOptions ...callopt.Option) (r *follow.FriendListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FriendList(ctx, Req)
}

func (p *kFollowServiceClient) ChatGroup(ctx context.Context, Req *follow.ChatGroupRequest, callOptions ...callopt.Option) (r *follow.ChatGroupResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChatGroup(ctx, Req)
}

func (p *kFollowServiceClient) JoinedChatGroupList(ctx context.Context, Req *follow.JoinedChatGroupListRequest, callOptions ...callopt.Option) (r *follow.JoinedChatGroupListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.JoinedChatGroupList(ctx, Req)
}

func (p *kFollowServiceClient) CreatedChatGroupList(ctx context.Context, Req *follow.CreatedChatGroupListRequest, callOptions ...callopt.Option) (r *follow.CreatedChatGroupListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreatedChatGroupList(ctx, Req)
}
