// Code generated by Kitex v0.15.2. DO NOT EDIT.
package followservice

import (
	server "github.com/cloudwego/kitex/server"
	follow "myreel/kitex_gen/follow"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler follow.FollowService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler follow.FollowService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
