// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	like "myreel/app/gateway/router/like"
	user "myreel/app/gateway/router/user"
	video "myreel/app/gateway/router/video"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	like.Register(r)

	video.Register(r)

	user.Register(r)

}
