// Code generated by hertz generator.

package like

import (
	"context"

	api "myreel/app/gateway/model/api/like"
	"myreel/app/gateway/pack"
	"myreel/app/gateway/rpc"
	"myreel/kitex_gen/like"
	"myreel/pkg/constants"
	"myreel/pkg/errno"

	"github.com/cloudwego/hertz/pkg/app"
)

// LikeAction .
// @router /like/action [POST]
func LikeAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.LikeActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamVerifyError.WithError(err))
		return
	}

	val, exist := c.Get(constants.CtxUserIdKey)
	if !exist {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}
	uid, ok := val.(int64)
	if !ok {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}

	err = rpc.LikeActionRPC(ctx, &like.LikeActionRequest{
		VideoId:    req.VideoId,
		CommentId:  req.CommentId,
		ActionType: req.ActionType,
		UserId:     uid,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespSuccess(c)
}

// LikeList .
// @router /like/list [GET]
func LikeList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.LikeListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamVerifyError.WithError(err))
		return
	}

	val, exist := c.Get(constants.CtxUserIdKey)
	if !exist {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}
	uid, ok := val.(int64)
	if !ok {
		pack.RespError(c, errno.NewErrNo(errno.ParamVerifyErrorCode, "failed to parse user id"))
		return
	}

	data, err := rpc.LikeListRPC(ctx, &like.LikeListRequest{
		Uid:    uid,
		Cursor: req.Cursor,
		Limit:  req.Limit,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	pack.RespData(c, data)
}
