// Code generated by Kitex v0.15.2. DO NOT EDIT.

package chat

import (
	"context"
	"myreel/kitex_gen/model"
	"strconv"

	"github.com/cloudwego/prutal"
)

// 消息类型
type ChatType int32

const (
	ChatType_CHAT_TYPE_PRIVATE ChatType = 0 // 私聊（proto3 要求第一个枚举值为 0）
	ChatType_CHAT_TYPE_GROUP   ChatType = 1 // 群聊
)

// Enum value maps for ChatType.
var ChatType_name = map[int32]string{
	0: "CHAT_TYPE_PRIVATE",
	1: "CHAT_TYPE_GROUP",
}

var ChatType_value = map[string]int32{
	"CHAT_TYPE_PRIVATE": 0,
	"CHAT_TYPE_GROUP":   1,
}

func (x ChatType) String() string {
	s, ok := ChatType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// 1. 发送私聊/群聊消息
type SendMessageRequest struct {
	SenderId int64    `protobuf:"varint,1,opt,name=sender_id" json:"sender_id,omitempty"`
	TargetId int64    `protobuf:"varint,2,opt,name=target_id" json:"target_id,omitempty"` // 私聊: receiver_id; 群聊: group_id
	ChatType ChatType `protobuf:"varint,3,opt,name=chat_type" json:"chat_type,omitempty"`
	Content  string   `protobuf:"bytes,4,opt,name=content" json:"content,omitempty"`
}

func (x *SendMessageRequest) Reset() { *x = SendMessageRequest{} }

func (x *SendMessageRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SendMessageRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SendMessageRequest) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *SendMessageRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *SendMessageRequest) GetChatType() ChatType {
	if x != nil {
		return x.ChatType
	}
	return ChatType_CHAT_TYPE_PRIVATE
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SendMessageResponse struct {
	Base *model.BaseResp `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
}

func (x *SendMessageResponse) Reset() { *x = SendMessageResponse{} }

func (x *SendMessageResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SendMessageResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SendMessageResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

// 2. 获取历史记录（私聊/群聊通用）
type GetHistoryRequest struct {
	UserId   int64    `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	TargetId int64    `protobuf:"varint,2,opt,name=target_id" json:"target_id,omitempty"` // 对方ID 或 群ID
	ChatType ChatType `protobuf:"varint,3,opt,name=chat_type" json:"chat_type,omitempty"`
	Cursor   int64    `protobuf:"varint,4,opt,name=cursor" json:"cursor,omitempty"` // 分页游标（可为空）
	Limit    int64    `protobuf:"varint,5,opt,name=limit" json:"limit,omitempty"`   // 默认在代码中设为 20，proto 不支持默认值（proto3）
}

func (x *GetHistoryRequest) Reset() { *x = GetHistoryRequest{} }

func (x *GetHistoryRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetHistoryRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetHistoryRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetHistoryRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *GetHistoryRequest) GetChatType() ChatType {
	if x != nil {
		return x.ChatType
	}
	return ChatType_CHAT_TYPE_PRIVATE
}

func (x *GetHistoryRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *GetHistoryRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Message struct {
	Id        int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	SenderId  int64  `protobuf:"varint,2,opt,name=sender_id" json:"sender_id,omitempty"`
	TargetId  int64  `protobuf:"varint,3,opt,name=target_id" json:"target_id,omitempty"`
	Content   string `protobuf:"bytes,4,opt,name=content" json:"content,omitempty"`
	CreatedAt int64  `protobuf:"varint,5,opt,name=created_at" json:"created_at,omitempty"`
}

func (x *Message) Reset() { *x = Message{} }

func (x *Message) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Message) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Message) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Message) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type Pagination struct {
	NextCursor int64 `protobuf:"varint,1,opt,name=nextCursor" json:"nextCursor,omitempty"`
	PrevCursor int64 `protobuf:"varint,2,opt,name=prevCursor" json:"prevCursor,omitempty"`
	Total      int64 `protobuf:"varint,3,opt,name=total" json:"total,omitempty"`
}

func (x *Pagination) Reset() { *x = Pagination{} }

func (x *Pagination) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Pagination) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Pagination) GetNextCursor() int64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

func (x *Pagination) GetPrevCursor() int64 {
	if x != nil {
		return x.PrevCursor
	}
	return 0
}

func (x *Pagination) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type MessageList struct {
	Messages   []*Message  `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty"`
	Pagination *Pagination `protobuf:"bytes,2,opt,name=pagination" json:"pagination,omitempty"`
}

func (x *MessageList) Reset() { *x = MessageList{} }

func (x *MessageList) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MessageList) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MessageList) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *MessageList) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetHistoryResponse struct {
	Base *model.BaseResp `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	Data *MessageList    `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (x *GetHistoryResponse) Reset() { *x = GetHistoryResponse{} }

func (x *GetHistoryResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetHistoryResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetHistoryResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetHistoryResponse) GetData() *MessageList {
	if x != nil {
		return x.Data
	}
	return nil
}

// 3. 获取未读消息（通常只用于私聊）
type GetUnreadRequest struct {
	UserId   int64    `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	TargetId int64    `protobuf:"varint,2,opt,name=target_id" json:"target_id,omitempty"` // 对方ID 或 群ID
	ChatType ChatType `protobuf:"varint,3,opt,name=chat_type" json:"chat_type,omitempty"`
}

func (x *GetUnreadRequest) Reset() { *x = GetUnreadRequest{} }

func (x *GetUnreadRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetUnreadRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUnreadRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUnreadRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *GetUnreadRequest) GetChatType() ChatType {
	if x != nil {
		return x.ChatType
	}
	return ChatType_CHAT_TYPE_PRIVATE
}

type GetUnreadResponse struct {
	Base *model.BaseResp `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	Data *MessageList    `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (x *GetUnreadResponse) Reset() { *x = GetUnreadResponse{} }

func (x *GetUnreadResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetUnreadResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUnreadResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetUnreadResponse) GetData() *MessageList {
	if x != nil {
		return x.Data
	}
	return nil
}

type ChatService interface {
	SendMessage(ctx context.Context, req *SendMessageRequest) (res *SendMessageResponse, err error)
	GetHistory(ctx context.Context, req *GetHistoryRequest) (res *GetHistoryResponse, err error)
	GetUnread(ctx context.Context, req *GetUnreadRequest) (res *GetUnreadResponse, err error)
}
