// Code generated by Kitex v0.15.2. DO NOT EDIT.

package user

import (
	"context"
	"myreel/kitex_gen/model"

	"github.com/cloudwego/prutal"
)

type User struct {
	Id        int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Username  string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Password  string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	AvatarUrl string `protobuf:"bytes,4,opt,name=avatarUrl" json:"avatarUrl,omitempty"`
	CreatedAt string `protobuf:"bytes,5,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt string `protobuf:"bytes,6,opt,name=updatedAt" json:"updatedAt,omitempty"`
	DeletedAt string `protobuf:"bytes,7,opt,name=deletedAt" json:"deletedAt,omitempty"`
}

func (x *User) Reset() { *x = User{} }

func (x *User) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *User) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *User) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *User) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

type LoginRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Code     string `protobuf:"bytes,3,opt,name=code" json:"code,omitempty"`
}

func (x *LoginRequest) Reset() { *x = LoginRequest{} }

func (x *LoginRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *LoginRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type Token struct {
	AccessToken       string `protobuf:"bytes,1,opt,name=accessToken" json:"accessToken,omitempty"`
	AccessExpireTime  int64  `protobuf:"varint,2,opt,name=accessExpireTime" json:"accessExpireTime,omitempty"`
	RefreshToken      string `protobuf:"bytes,3,opt,name=refreshToken" json:"refreshToken,omitempty"`
	RefreshExpireTime int64  `protobuf:"varint,4,opt,name=refreshExpireTime" json:"refreshExpireTime,omitempty"`
}

func (x *Token) Reset() { *x = Token{} }

func (x *Token) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Token) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Token) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *Token) GetAccessExpireTime() int64 {
	if x != nil {
		return x.AccessExpireTime
	}
	return 0
}

func (x *Token) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *Token) GetRefreshExpireTime() int64 {
	if x != nil {
		return x.RefreshExpireTime
	}
	return 0
}

type UserWithToken struct {
	User  *User  `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Token *Token `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (x *UserWithToken) Reset() { *x = UserWithToken{} }

func (x *UserWithToken) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserWithToken) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserWithToken) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserWithToken) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type LoginResponse struct {
	Base *model.BaseResp `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	Data *UserWithToken  `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (x *LoginResponse) Reset() { *x = LoginResponse{} }

func (x *LoginResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *LoginResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LoginResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *LoginResponse) GetData() *UserWithToken {
	if x != nil {
		return x.Data
	}
	return nil
}

type RegisterRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (x *RegisterRequest) Reset() { *x = RegisterRequest{} }

func (x *RegisterRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RegisterRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	Base *model.BaseResp `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
}

func (x *RegisterResponse) Reset() { *x = RegisterResponse{} }

func (x *RegisterResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RegisterResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RegisterResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

type GetUserInfoRequest struct {
	UserId int64 `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
}

func (x *GetUserInfoRequest) Reset() { *x = GetUserInfoRequest{} }

func (x *GetUserInfoRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetUserInfoRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserInfoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserInfoResponse struct {
	Base *model.BaseResp `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	Data *User           `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (x *GetUserInfoResponse) Reset() { *x = GetUserInfoResponse{} }

func (x *GetUserInfoResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetUserInfoResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserInfoResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetUserInfoResponse) GetData() *User {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetUploadTokenRequest struct {
	Suffix string `protobuf:"bytes,1,opt,name=suffix" json:"suffix,omitempty"`
	UserId int64  `protobuf:"varint,2,opt,name=userId" json:"userId,omitempty"`
}

func (x *GetUploadTokenRequest) Reset() { *x = GetUploadTokenRequest{} }

func (x *GetUploadTokenRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetUploadTokenRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUploadTokenRequest) GetSuffix() string {
	if x != nil {
		return x.Suffix
	}
	return ""
}

func (x *GetUploadTokenRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUploadTokenResponse struct {
	Base *model.BaseResp   `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	Data *model.UpyunToken `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (x *GetUploadTokenResponse) Reset() { *x = GetUploadTokenResponse{} }

func (x *GetUploadTokenResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetUploadTokenResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUploadTokenResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetUploadTokenResponse) GetData() *model.UpyunToken {
	if x != nil {
		return x.Data
	}
	return nil
}

type AvatarNotifyRequest struct {
	Url string `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
}

func (x *AvatarNotifyRequest) Reset() { *x = AvatarNotifyRequest{} }

func (x *AvatarNotifyRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *AvatarNotifyRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *AvatarNotifyRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AvatarNotifyResponse struct {
}

func (x *AvatarNotifyResponse) Reset() { *x = AvatarNotifyResponse{} }

func (x *AvatarNotifyResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *AvatarNotifyResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type MFA struct {
	Secret string `protobuf:"bytes,1,opt,name=secret" json:"secret,omitempty"`
	Qrcode string `protobuf:"bytes,2,opt,name=qrcode" json:"qrcode,omitempty"`
}

func (x *MFA) Reset() { *x = MFA{} }

func (x *MFA) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MFA) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MFA) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *MFA) GetQrcode() string {
	if x != nil {
		return x.Qrcode
	}
	return ""
}

type GetMFARequest struct {
}

func (x *GetMFARequest) Reset() { *x = GetMFARequest{} }

func (x *GetMFARequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetMFARequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type GetMFAResponse struct {
	Base *model.BaseResp `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	Data *MFA            `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (x *GetMFAResponse) Reset() { *x = GetMFAResponse{} }

func (x *GetMFAResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetMFAResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetMFAResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetMFAResponse) GetData() *MFA {
	if x != nil {
		return x.Data
	}
	return nil
}

type BindMFARequest struct {
	Code   string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Secret string `protobuf:"bytes,2,opt,name=secret" json:"secret,omitempty"`
}

func (x *BindMFARequest) Reset() { *x = BindMFARequest{} }

func (x *BindMFARequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *BindMFARequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *BindMFARequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *BindMFARequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type BindMFAResponse struct {
	Base *model.BaseResp `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
}

func (x *BindMFAResponse) Reset() { *x = BindMFAResponse{} }

func (x *BindMFAResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *BindMFAResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *BindMFAResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

type SearchImgRequest struct {
	Data string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (x *SearchImgRequest) Reset() { *x = SearchImgRequest{} }

func (x *SearchImgRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SearchImgRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchImgRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type SearchImgResponse struct {
	Base *model.BaseResp `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	Data string          `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (x *SearchImgResponse) Reset() { *x = SearchImgResponse{} }

func (x *SearchImgResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SearchImgResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchImgResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *SearchImgResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type RefreshRequest struct {
	Token  string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	UserId int64  `protobuf:"varint,2,opt,name=userId" json:"userId,omitempty"`
}

func (x *RefreshRequest) Reset() { *x = RefreshRequest{} }

func (x *RefreshRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RefreshRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RefreshRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RefreshRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RefreshResponse struct {
	Base  *model.BaseResp `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	Token string          `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (x *RefreshResponse) Reset() { *x = RefreshResponse{} }

func (x *RefreshResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RefreshResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RefreshResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *RefreshResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UserService interface {
	Login(ctx context.Context, req *LoginRequest) (res *LoginResponse, err error)
	Register(ctx context.Context, req *RegisterRequest) (res *RegisterResponse, err error)
	GetUserInfo(ctx context.Context, req *GetUserInfoRequest) (res *GetUserInfoResponse, err error)
	GetUploadToken(ctx context.Context, req *GetUploadTokenRequest) (res *GetUploadTokenResponse, err error)
	GetMFA(ctx context.Context, req *GetMFARequest) (res *GetMFAResponse, err error)
	BindMFA(ctx context.Context, req *BindMFARequest) (res *BindMFAResponse, err error)
	SearchImg(ctx context.Context, req *SearchImgRequest) (res *SearchImgResponse, err error)
	Refresh(ctx context.Context, req *RefreshRequest) (res *RefreshResponse, err error)
	AvatarNotify(ctx context.Context, req *AvatarNotifyRequest) (res *AvatarNotifyResponse, err error)
}
